# Generated by Django 3.1.4 on 2020-12-07 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, verbose_name='Имя владельца задачаи')),
                ('task_name', models.CharField(max_length=60, verbose_name='Название задачи')),
                ('task_text', models.TextField(verbose_name='Описание задачи')),
                ('task_status', models.CharField(max_length=20, verbose_name='Статус задачи')),
                ('end_date', models.DateTimeField(verbose_name='Дата создания')),
                ('start_date', models.DateTimeField(verbose_name='Дата создания')),
            ],
        ),
    ]
